batch_size: 5120
dataset: pretrain
drop_ratio: 0.5
emb_dim: 300
epochs: 300
gpu_id: 0
initw_name: default
lr: 0.01
model: gin-virtual
model_path: ckpt/pretrain.pt
n_steps: 1
no_print: false
norm_layer: batch_norm
num_layer: 5
num_workers: 0
patience: 50
readout: sum
trails: 2
walk_length: 3
wdecay: 1.0e-05
